### ISSUE TITLE
fixed navbar

### ISSUE THREAD

**Issue by gyawaliamit7** [CSCIClub/CSCIClub.github.io#8]
Should we try to implement fixed navbar so that navbar appears when we scroll down the page
?

<img width="711" alt="Screen Shot 2020-02-26 at 11 54 47 PM" src="https://user-images.githubusercontent.com/34220616/75416230-64395e80-58f3-11ea-90bb-cb8f3f75016c.png">

**Comment by prashulstha** [comment]
Fixed: [Commit](https://github.com/CSCIClub/CSCIClub.github.io/commit/0aff84e8b2f3005664b34a1d978ea0382b324bbf)
